collections:
  projects:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      type: "projects"
    values:
      layout: project

exclude:
- ".DS_Store"
- ".gitignore"
- Gemfile
- Gemfile.lock
- README.md
