collections:
  projects:
    output: true
  pages:
    output: true
    permalink: /:slug/

defaults:
  -
    scope:
      type: projects
    values:
      layout: project

theme: null

exclude:
  - ".DS_Store"
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - README.md
